# Generated by Django 3.0.7 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0004_remove_customuser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('profile_pic', models.FileField(upload_to=teacher.models.upload_profile)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
