# Generated by Django 3.0.7 on 2021-06-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='Subjects',
            field=models.ManyToManyField(to='course.Subjects'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='material',
            name='file_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.MyClass'),
        ),
    ]
