# Generated by Django 3.0.7 on 2021-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210623_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_superadmin',
            new_name='is_student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
