# Generated by Django 3.0.7 on 2021-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_hr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_registrar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('student', 'student'), ('teacher', 'teacher'), ('hod', 'hod'), ('hr', 'hr'), ('accountant', 'accountant'), ('registrar', 'registrar')], default='', max_length=50),
        ),
    ]
