# Generated by Django 3.0.7 on 2021-06-25 18:14

import accountant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('profile_pic', models.FileField(upload_to=accountant.models.upload_profile_pic)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Online', 'Online'), ('cash', 'Offline')], max_length=10)),
                ('amount_paid', models.FloatField(blank=True, default=None)),
                ('txn_id', models.CharField(default=uuid.UUID('d98e83f5-f832-4bef-8726-643712458c49'), max_length=100)),
                ('status', models.CharField(default=False, max_length=10)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
