# Generated by Django 3.0.7 on 2021-07-08 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210708_2249'),
        ('accountant', '0002_auto_20210708_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Fee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('7522bb87-a7d2-42af-b818-e691699bfa36'), max_length=100),
        ),
    ]
