# Generated by Django 3.0.7 on 2021-06-27 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_auto_20210625_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(default=uuid.UUID('3cc74481-5d29-4503-ba2a-534d522e5d21'), max_length=100),
        ),
    ]
