# Generated by Django 3.0.7 on 2021-06-27 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_auto_20210627_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(default=uuid.UUID('fe19676e-485c-4ac8-ad16-e776c7c04c80'), max_length=100),
        ),
    ]
