# Generated by Django 3.0.7 on 2021-06-27 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_auto_20210627_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(default=uuid.UUID('a2f52a81-b9c0-4376-a8df-274d3ef3dfd0'), max_length=100),
        ),
    ]
