# Generated by Django 3.0.7 on 2021-06-27 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20210627_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(default=uuid.UUID('1d7c819c-e191-4d58-bf9a-f4cace56f7d3'), max_length=100),
        ),
    ]
