# Generated by Django 3.0.7 on 2021-07-28 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20210729_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('ee113a08-0180-410b-b469-ea2d7efe0768'), max_length=100),
        ),
    ]
