# Generated by Django 3.0.7 on 2021-06-28 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_auto_20210627_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(default=uuid.UUID('b1b1f323-191a-44f8-b3ea-fc364745a8ae'), max_length=100),
        ),
    ]
