# Generated by Django 3.1.2 on 2021-08-03 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_auto_20210729_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('5df20541-59d9-431c-b43c-1fd028a57a8f'), max_length=100),
        ),
    ]
