# Generated by Django 3.1.2 on 2021-08-03 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0007_auto_20210803_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('e0a8e08c-ef5e-4e76-a19f-5fe1d5310a00'), max_length=100),
        ),
    ]
