# Generated by Django 3.1.2 on 2021-08-03 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0008_auto_20210804_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('c5cd9ce1-8c42-460a-8d20-8cfa3d5db72e'), max_length=100),
        ),
    ]
