# Generated by Django 3.1.2 on 2021-08-03 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0009_auto_20210804_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('ff8f3531-37ae-417d-a5af-d4b123458adf'), max_length=100),
        ),
    ]
