# Generated by Django 3.1.2 on 2021-08-05 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0011_auto_20210804_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('5582d5fd-46c2-496c-aee9-de143ace7118'), max_length=100),
        ),
    ]
