# Generated by Django 3.2.4 on 2021-08-21 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0012_auto_20210805_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('bb65639a-cb4d-4c59-b3bb-cf8f5e21d555'), max_length=100),
        ),
    ]
