# Generated by Django 3.2.4 on 2021-08-21 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0013_auto_20210822_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('7dba3bfd-3f95-4393-94c1-d819c33c86c3'), max_length=100),
        ),
    ]
