# Generated by Django 3.2.4 on 2021-08-21 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0014_auto_20210822_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, default=uuid.UUID('51663b99-505e-4210-824f-55cdfd9fc398'), max_length=100),
        ),
    ]
