# Generated by Django 3.0.7 on 2021-06-25 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('date_of_birth', models.DateField(blank=True, default='')),
                ('profile_pic', models.FileField(blank=True, default='', upload_to=student.models.upload_profile_pic)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semester', models.IntegerField(blank=True, default=1)),
                ('payment_approved', models.BooleanField(blank=True, default=False)),
                ('student_approved', models.BooleanField(blank=True, default=False)),
                ('academic_year', models.CharField(blank=True, default='2020-21', max_length=10)),
                ('admission_id', models.CharField(blank=True, default='', max_length=100)),
                ('degree', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Degree')),
            ],
        ),
    ]
