# Generated by Django 3.0.7 on 2021-06-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('administrator', '0004_remove_customuser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('date_of_birth', models.DateField(default='')),
                ('profile_pic', models.FileField(default='', upload_to=student.models.upload_profile_pic)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semester', models.IntegerField(default=1)),
                ('payment_approved', models.BooleanField(blank=True, default=False)),
                ('student_approved', models.BooleanField(blank=True, default=False)),
                ('admission_id', models.CharField(default='', max_length=100)),
                ('academic_year', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.AcademicYear')),
                ('degree', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Degree')),
            ],
        ),
    ]
