# Generated by Django 3.0.7 on 2021-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
