# Generated by Django 3.0.7 on 2021-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.IntegerField()),
                ('course_intrested', models.CharField(max_length=60)),
            ],
        ),
    ]
