# Generated by Django 3.0.7 on 2021-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='course_intrested',
            new_name='course_interested',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
