# Generated by Django 3.1.2 on 2021-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210804_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emirates_id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
