# Generated by Django 3.1.2 on 2021-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210804_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transfer_college_academic_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_college_city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_college_country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_college_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
