# Generated by Django 3.1.2 on 2021-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210804_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
