# Generated by Django 3.1.2 on 2021-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210804_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='home_telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('divorced', 'Divorced')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='post_box',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, default='2020-21', max_length=20),
        ),
    ]
